### ISSUE TITLE
(Question) Persist / Preload collections?

### ISSUE THREAD

**Issue by 0x1a0b** [hoppscotch/hoppscotch#1068]
From reading the documentation I understood that collections are saved in the localstorage of the browser. There is also an option to share them via Google/Github.

**Describe the solution you'd like**

Is it also possible to perload / seed collections from the disk or another webserver? I am looking for a way to bake default collections into a container ontop of the installed postwoman container. Eg today I have a container with aixigo/arestocats installed where I can just add the collections as text files into a new container ontop of the installation base.

**Additional context**
This is a semi-airgapped environment where sharing via google/github is a no-go and the user that starts postwoman should be greeted by default collections

**Comment by Earl-Brown** [comment]
As a developer looking to integrate Hoppscotch/Postwoman into our Agile cycle, **I'd** like to be able to open/save collections/environments/workspaces to our development folder so that changes are automatically included in our source control system.  (Kind of an easier/more flexible github integration).

What would work best for me is to have the workspace include collections and environments.  This makes it easy for the QA group to use the same tests the Dev group uses, but just switch the environment.  And for dev to use the tests QA creates for their needs.

Plus, it would make it easier to integrate into our automated build/test/release system.

**Comment by programster** [comment]
+1 for just having a docker volume store the collections/environments/workspaces in files in a "state"/"storage" volume. I would like to be able to share collections with others by sending them file(s), and be able to persist my collection across container wipes without relying on browser storage, Github, or Google.

**Comment by Bowrna** [comment]
hi, @liyasthomas could I take up this issue?  I will need help before starting my work on this. what is the best way to get help?

**Comment by liyasthomas** [comment]
Hi @Bowrna, feel free to pick up this feature request. [Contact us](https://github.com/hoppscotch/hoppscotch#support) for any help.

**Comment by liyasthomas** [comment]
Closing this issue in favor of #2020.
