### ISSUE TITLE
Error: Proxy Error. Check console for details - again

### ISSUE THREAD

**Issue by Siccity** [hoppscotch/hoppscotch#1089]
Almost same issue as #1027 but this time with different errors in the console.
![image](https://user-images.githubusercontent.com/6402525/90370208-52986e80-e06d-11ea-9067-7629db64605b.png)

**Comment by liyasthomas** [comment]
We've migrated out site from https://postwoman.io to https://hoppscotch.io. Can you confirm you're having this issue in https://hoppscotch.io ?

_You'll be automatically redirected from https://postwoman.io to https://hoppscotch.io from today onwards._

**Comment by Siccity** [comment]
Yes, the new site seems to work.
What is the reason for the sudden name change if I may ask? I always liked postwoman as a juxtaposition to postman

**Comment by liyasthomas** [comment]
1. Similarity in name with "Postman" may introduce trademark violations in future.
We don't want to hurt any other project's goodwill.

2. Rather than being an "alternative to Postman", we focus to become the best available testing suite in web.

Our new identity aligns with our new focus — to provide the best open source testing suite in web.

_Here my announcement on changing the name: https://dev.to/liyasthomas/postwoman-is-changing-name-igp_

Closing this issue since it's resolved.
