### ISSUE TITLE
Add session persistence to realtime tabs

### ISSUE THREAD

**Issue by LuisMayo** [hoppscotch/hoppscotch#1196]
**Describe the solution you'd like**
I'd like for all tabs under "realtime" category to persist when I switch categories, in the same fashion as "Home" and "GraphQL" work.
Example: You change the address of the websocket server you're testing, then you suddenly realize you want to test a simple HTTP request so you go back to "home". When you're done you go back to the websockets section, only to find out the address has been replaced by the default WS address

**Describe alternatives you've considered**
It's not something that terrible, you could just, re-type the websocket address or maybe open another tab of hoppscotch if you want not to lose current "realtime" settings

**Additional context**
It's not compulsory or really important, I think it'd be convenient and it'd make realtime consistent with the other categories

**Comment by badsketch** [comment]
Hey I'd like to contribute and give this a shot 🙂

**Comment by liyasthomas** [comment]
@badsketch feel free to contribute. You're welcome. Let me know if you need any help.

**Comment by badsketch** [comment]
>You change the address of the websocket server you're testing, then you suddenly realize you want to test a simple HTTP request so you go back to "home". When you're done you go back to the websockets section, only to find out the address has been replaced by the default WS address

By session persistence do we also want to persist the connection? Currently, after successfully connecting, then switching to a different category (for ex. Home), then coming back to realtime, it goes back to `(waiting for connection)`. Do we want to maintain this connection as well or do we just want to persist the url?

**Comment by LeoMartinDev** [comment]
> > You change the address of the websocket server you're testing, then you suddenly realize you want to test a simple HTTP request so you go back to "home". When you're done you go back to the websockets section, only to find out the address has been replaced by the default WS address
> 
> By session persistence do we also want to persist the connection? Currently, after successfully connecting, then switching to a different category (for ex. Home), then coming back to realtime, it goes back to `(waiting for connection)`. Do we want to maintain this connection as well or do we just want to persist the url?

Keeping the connection up sounds nice

**Comment by LeoMartinDev** [comment]
Hey @badsketch ! Do you need help on that ?

**Comment by badsketch** [comment]
Hi @LeoMartinDev, not at the moment. Thank you very much for offering though and for the earlier reply to my question.

**Comment by LuisMayo** [comment]
> > You change the address of the websocket server you're testing, then you suddenly realize you want to test a simple HTTP request so you go back to "home". When you're done you go back to the websockets section, only to find out the address has been replaced by the default WS address
> 
> By session persistence do we also want to persist the connection? Currently, after successfully connecting, then switching to a different category (for ex. Home), then coming back to realtime, it goes back to `(waiting for connection)`. Do we want to maintain this connection as well or do we just want to persist the url?

Project maintainers should decide on that, personally I think it'd be cool but I haven't checked the codebase so I don't know whether it's possible or not

**Comment by badsketch** [comment]
Could you weigh in @liyasthomas? 

I saw that input fields like request url, graphql editor, are persisted using $store, and `vuex-persist` places the store in local storage. This works well with http (not sure if this is the right word) tabs like REST and graphql tab. But for realtime, because we're maintaining a collection,  I think we might get into a weird state if someone cleared storage?

1. connect to socket 
2. connectionState is set to true in $store as well as in localStorage (connect button now says 'disconnect')
3. user refreshes 
4. connectionState is still true so connect button still says 'disconnect' // this is fine
5. user clears local storage // this is not fine
6. user refreshes
7. connectionState is false so connect button now says 'connect', BUT there's no way to disconnect the previous socket connection

Hope I didn't miss anything. For this reason, maybe we should leave socket connection out of persistence, but keep the realtime logs and add a separate button to clear the log? Thoughts?

**Comment by LeoMartinDev** [comment]
Do not persist `connectionState` and it should work well IMO

**Comment by badsketch** [comment]
yeah my main concern was just that we would have connections left over, but when you say the connections close on refresh, then I guess that shouldn't be a problem. thanks for the clarification. I'll keep in mind your suggestions

**Comment by badsketch** [comment]
I was able to persist everything on tab change and on refresh 🙂. I'm a little concerned about refresh though, because the socket can't listen to "onclose" when the page is refreshed, so there's not much indication that the socket has disconnected. The log doesn't say that there has been a disconnect.
![hoppscotch_realtime](https://user-images.githubusercontent.com/8953212/95691020-dabc6f80-0be9-11eb-9b6b-f70b7fdec388.gif)
Is it worth fabricating a disconnect message and inserting it in the log? I was thinking we could also exclude these realtime tabs from `vuex-persist` so no persisting upon refresh. It's more drastic, but maybe more intuitive for UX. Thoughts?

**Comment by liyasthomas** [comment]
I guess we should push a "disconnected log" on refresh. That would be the better UX.

**Comment by liyasthomas** [comment]
@badsketch ready for the PR?

**Comment by badsketch** [comment]
Hey really sorry for the delay. I’ll have 3 of the tabs working very soon.
I think I’ll submit a draft PR by tomorrow to get some help on the socketIO
tab because I get mutation errors after placing it in vuex. Is that
alright?

**Comment by liyasthomas** [comment]
Sounds good, glad to help you.

**Comment by LeoMartinDev** [comment]
What about this issue ? Shouldnt it be closed as the PR has been merged ?

**Comment by LuisMayo** [comment]
I'd say not since it's not in master yet

**Comment by 0xc0Der** [comment]
what about this. can i work on it?

**Comment by liyasthomas** [comment]
Hi @0xc0Der, feel free to pick this up.

NOTE: implementation in #1298 is stale and now we uses localPersistence and dispatching store instances instead of Vuex store.

**Comment by liyasthomas** [comment]
Implemented in #1952.

**Comment by AndrewBastin** [comment]
Actually @liyasthomas a quick hotfix so that the Realtime page will remember the last page will be cool.

**Comment by liyasthomas** [comment]
We can track the persistence of the active tab in another issue, hence closing.
