### ISSUE TITLE
Docker Volume mount to store Data externally

### ISSUE THREAD

**Issue by markusressel** [hoppscotch/hoppscotch#1309]
Hi there,
I really like the project and would like to run it using Docker.
However, I always use volume mounts to store application externally (not inside the docker volume stuff), but there is no example of how to do that anywhere. I have found [this PR](https://github.com/hoppscotch/hoppscotch/pull/340) that claims to add a volume definition, but in fact doesn't.

Where does hoppscotch store its data?  
Is it a file, a directory, or is it even possible to use an externally hosted database like postgres for that?

Thx!

**EDIT**:
I just found https://github.com/hoppscotch/hoppscotch/issues/1068 with seems to ask for a similar thing.
Just to clarify why I am asking:
I am accessing hoppscotch from multiple devices, and update the docker container automatically, which is deployed inside of a small kubernetes cluster. The last time I updated the container all data I had set up previously was lost, which was a real inconvenience, so I am looking for a way to preserver application data.

**Comment by liyasthomas** [comment]
As of now, data sync is only available if you've been signed in with Google / GitHub. This is because at the time of writing sync feature, I went with Firebase Firestore DB — since I was using Firebase Auth. But now we're working on decoupling Firebase from the app and support multiple ways to enable users to load and sync collections from a file irrespective of its location (Git repo, Google Drive, Local file, external file / DB etc). Which will ultimately solve this issue. You can find it's active discussion over #870 .

And for this specific issue with Docker, well if you sign in with Google / GitHub, your collections will be synced to Firestore and can be accessed from any instances. And when signed out, it stays inside docker images ~browsers localstorage not being accessible to other instances.

**Comment by liyasthomas** [comment]
I guess this issues can be addressed further in #870, hence closing.
