### ISSUE TITLE
Too much permissions for GitHub Auth 

### ISSUE THREAD

**Issue by yhnavein** [hoppscotch/hoppscotch#1377]
**Describe the bug**
When you want to authenticate with GitHub there is definitely too much permissions being requested. Giving WRITE access to all of my repositories and gists (public and private) is a big no-no. It's potentially a security issue.

**To Reproduce**
1. From the browser: Go to https://hoppscotch.io
2. Click on Login with Github
3. OAuth screen from GitHub is presented with too much permissions requested

**Expected behavior**
Only permissions to see user's email is expected

**Screenshots**
![image](https://user-images.githubusercontent.com/516709/101758985-4f703500-3ad9-11eb-91b8-02d26620c7ac.png)

**Comment by liyasthomas** [comment]
#@yhnavein well, that's certainly not the case. Since #1367 you can now sync collections and environments with your gist. In near future we're also going to add syncing with repositories. And this feature is only active for users who've signed in with GitHub. So that explains why Hoppscotch GitHub OAuth app requires gist and repo permissions. Since you raised this concern, I'll turn off repo permission for now since that feature is a WIP. But gist permission is mandatory to activate all the above mentioned feature. Thanks for reaching out. Will be turning off repo permissions for now.
