### ISSUE TITLE
CORS header missing

### ISSUE THREAD

**Issue by MatanAmoyal** [hoppscotch/hoppscotch#1399]
Hello,

I installed the latest docker version of hoppscotch (release on 22.12.20) and i installed it in my laptop and in k8s.
The UI is working, and the request example (https://httpbin.org/get) is working..

but when i'm trying to do another request to my app, it failed on CORS header missing..

 i tried to add Access-Control-Allow-Origin: * to header without success.
Also tried to installed the extension to browser - firefox and chrome... but same...

Maybe do you have any advise about it?

**Comment by liyasthomas** [comment]
`Access-Control-Allow-Origin` is a response header, not a request header. You should enable it from your apps side (server side).

[Stack Overflow reference](https://stackoverflow.com/a/10636765)

Under normal circumstances `CORS` issues can be fixed by either browser extension or turning on the `Proxy mode` from [Settings](https://hoppscotch.io/settings).

Let me know if you still have issues with`CORS`.
