### ISSUE TITLE
All data is sent via OPTIONS when I use simple authentication on localhost

### ISSUE THREAD

**Issue by MassiveBox** [hoppscotch/hoppscotch#1454]
**Describe the bug**
When using Basic Auth on localhost, instead of using POST, GET, PUT, or any request type I set on Hoppscotch, my server receives a OPTIONS call. 

**To Reproduce**
1. Set as target URL a server running on LocalHost (idk if it's the same with external sites)
2. Turn off proxy
3. Open a server on localhost that listens for all requests
4. Set authorization on simple auhorization, input random data
5. Send request from hoppscotch
6. See error on server logs

**Expected behavior**
If I set as method GET, I'm supposed to see GET in the server logs. I've tried with ARC, and it works, so it's not a server-side problem.

**Screenshots**
![Error](https://telegra.ph/file/489958479ee06874798c7.png)

**Desktop (please complete the following information):**
 - OS: Rolling Arch
 - Browser: Chromium (ungoogled)
 - Version: 87.0.4280.88 (Official Build) Arch Linux (64-bit)

**Comment by liyasthomas** [comment]
This looks like a pre-flight request scenario.

Refer:
- [Dev.to - Why is my browser sending an OPTIONS HTTP request instead of POST?](https://dev.to/p0oker/why-is-my-browser-sending-an-options-http-request-instead-of-post-5621)
- [stack overflow - Why does the browser send an OPTIONS request even though my frontend code is just making a POST request?](https://stackoverflow.com/questions/46904400/why-does-the-browser-send-an-options-request-even-though-my-frontend-code-is-jus)
- [stack overflow - Why is an OPTIONS request sent and can I disable it?](https://stackoverflow.com/questions/29954037/why-is-an-options-request-sent-and-can-i-disable-it)

**Comment by liyasthomas** [comment]
Feel free to re-open this issue if it's not a pre-flight request.

**Comment by lostpebble** [comment]
I'm getting the same, just want to make a simple GET request to my localhost server- but Hoppscotch always sends an OPTIONS request instead. Is there no way to prevent the OPTIONS request?

**Comment by liyasthomas** [comment]
Yeah, that's a pre-flight request.
https://github.com/hoppscotch/hoppscotch/issues/1454#issuecomment-770245079
