### ISSUE TITLE
Error When install on centos 7

### ISSUE THREAD

**Issue by culunvb** [hoppscotch/hoppscotch#1552]
npm ERR! code 1
npm ERR! path /home/hoppscotch/node_modules/deasync
npm ERR! command failed
npm ERR! command sh -c node ./build.js
npm ERR! `linux-x64-node-15` exists; testing
npm ERR! Problem with the binary; manual build incoming
npm ERR! stdout=
npm ERR! err=Error: Command failed: /usr/bin/node quick-test.js
npm ERR! /home/hoppscotch/node_modules/bindings/bindings.js:135
npm ERR!   throw err;
npm ERR!   ^
npm ERR!

**Comment by liyasthomas** [comment]
@culunvb can you use the Bug report issue template to report an issue

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by culunvb** [comment]
Ooo, i'm sorry not given information error details. here's for detail Information.
1. OS ( Centos 7 x_64 bit )
2. NodeJs  version v15.12.0,
3. NPm  version 7.6.3

**Additional Context**
I found error when I  execute the command "npm install" in hoppscotch folder

**ScreenShot**
![image](https://user-images.githubusercontent.com/13093552/111908586-5e796280-8a8c-11eb-949f-466f2cc35ff0.png)

**Comment by liyasthomas** [comment]
Thanks for the detailed info. This doesn't look like an issue with Hoppscotch alone. Can you clean your npm cache `npm cache clean` and try installing dependencies again `npm i `

**Comment by liyasthomas** [comment]
Try deleting the `package-lock.json` file before `npm i`.
Feel free to re-open this issue if the issue still persists.
