### ISSUE TITLE
Self hosting hoppscotch

### ISSUE THREAD

**Issue by GerardPaligot** [hoppscotch/hoppscotch#1672]
Hello!

I would like to create a self host instance of hoppscotch on a Firebase project (I see this [wiki page](https://github.com/hoppscotch/hoppscotch/wiki/Hosting)) but I was surprised to see no backup of data in the serverless configuration.

After some search on the codebase, I can see a lot of GraphQL request to https://api.hoppscotch.io/graphql. Does it means that we can only self host the website and push all our collections to Hoppscotch servers or we can deploy the GraphQL api too?

Thanks in advance!

**Comment by liyasthomas** [comment]
Hoppscotch's backend GraphQL APIs hosted on `api.hoppscotch.io/graphql` is a part of the unreleased Teams Collaboration feature. This API does not effect any other services of Hoppscotch web client.

Currently, Teams collaboration feature is only released to [Beta users](https://github.com/hoppscotch/hoppscotch/wiki/Teams) for testing purposes. And once we complete enough testing with beta users - we'll be releasing the backend source code under same [Hoppscotch organization](https://github.com/hoppscotch).

Please feel free to self-host current Hoppscotch web client with Firebase as a backend provider. Down the line, once Teams feature lands on production we'll provide a migration guide (I can confirm it's 100% backward compatible) with instructions to self-host Hoppscotch backed server. On the client side, it'll be as simple as pulling the lastest commits from upstream.

Eventually we're planning to drop the Firebase dependencies and let users have full control over the data.

So, since teams feature isn't up on production yet and is currently restricted only to official `hoppscotch.io` origin - you can self-host the current version of Hoppscotch and migrate seamlessly to your own self-hosted backend once it's rolled out for public.

Thanks for the patience.

**Comment by GerardPaligot** [comment]
Thanks @liyasthomas for all these information! I'll deploy the project on my Firebase and will deploy a new version when teams feature will be merged too.
