### ISSUE TITLE
"multipart/form-data" in the list of content types

### ISSUE THREAD

**Issue by kaname-png** [hoppscotch/hoppscotch#1704]
**Is your feature request related to a problem? Please describe.**
No problem, but it would make it easier to choose the types of content in the requests.

**Describe the solution you'd like**
Show the content type "multipart/form-data" in the "Content types" list.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://user-images.githubusercontent.com/56084970/120928766-5603f180-c6a3-11eb-84dd-32474dd7e6a9.png)

**Comment by liyasthomas** [comment]
Hi @kaname-png, `multipart/form-data` is already in the drop-down list. Since the list is sorted in alphabetical order -  `multipart/form-data` got hidden from the first fold.

Please try typing in the first few characters of your desired `content-type` in the input box and you'll get suggestions according to it. Here's a screenshot of how you can choose  `multipart/form-data` from the list (I typed in few first characters).

![screely-1622991081452](https://user-images.githubusercontent.com/10395817/120929097-8d22d480-c69c-11eb-972b-d376c11318d5.png)

I hope this solves your issue - feel free to comment on any other better user case you'd like to see here or having any trouble with the list.

**Comment by kaname-png** [comment]
Yes, that's why I was saying that it would be more accessible if that type of content always appeared in the list and not just by typing its name.

**Comment by liyasthomas** [comment]
Oh I see - thank you for the suggestion. I'll fix it ASAP.

**Comment by liyasthomas** [comment]
I've replaced the auto-complete input with a drop-down input. Now you just have to click and choose your desired `content-type`. Hope it helps. Let me know if this solves you issues.

**Comment by kaname-png** [comment]
Yes, this solves my suggestion.
