### ISSUE TITLE
[feature]: Collection-wide headers and authorization

### ISSUE THREAD

**Issue by sawa-ko** [hoppscotch/hoppscotch#1741]
**Is your feature request related to a problem? Please describe.**
Yes, it is very annoying to be putting for example, the header of a Bearer Token in all requests and keep that header updated one by one.

**Describe the solution you'd like**
An option to assign to folders or collections of requests a set of global headers for the requests.

**Describe alternatives you've considered**
The current option is to do it one by one, something very annoying and exhausting.

**Additional context**
No.

**Comment by liyasthomas** [comment]
This is a good feature request. Will look into implementing it.

**Comment by Shylajhaa** [comment]
@liyasthomas Is this issue available to work on?

**Comment by liyasthomas** [comment]
Hi @Shylajhaa, yes this issue is available for you to pick up. Thanks for showing interest in contributing to Hoppscotch, feel free to ping us if you got stuck.

**Comment by Shylajhaa** [comment]
> Hi @Shylajhaa, yes this issue is available for you to pick up. Thanks for showing interest in contributing to Hoppscotch, feel free to ping us if you got stuck.

Thanks, @liyasthomas Can you assign it to me?

**Comment by kaname-png** [comment]
> Started working on this. Sharing my thoughts on design
> 
> 1. When clicking on Edit collection, another input box to get auth should be added with the options as available already (None, Basic auth, ...)
> 
> <img alt="Screenshot 2021-10-20 at 12 38 56 AM" width="549" src="https://user-images.githubusercontent.com/22257998/137975240-2d5fe614-da7a-4cfe-bb8b-e8bf368d3ff9.png">
> 
> 1. In the auth tab of a request, Inherit auth from parent option should be added.
> 
> <img alt="Screenshot 2021-10-20 at 12 41 32 AM" width="242" src="https://user-images.githubusercontent.com/22257998/137975380-7dea3196-a1b5-4c83-8755-9a187fe73780.png">
> 
> 1. When sending a request, the auth info from parent collection will be used
> 
> @liyasthomas Let me know if I'm missing anything here.

But will that work only for the Authorization field of the Header or for everything in the Header?

**Comment by Shylajhaa** [comment]
@liyasthomas Apologies for the delayed response. I will start looking into the design suggested by you and would like to work on this feature.

**Comment by Shylajhaa** [comment]
@liyasthomas @kaname-png The environment approach will solve the problem, but only seems like a workaround. That might not be an ideal situation given that there could be several API endpoints grouped under individual folders with all of these folders sharing a common environment.

The Global-Local headers solution sounds like a suitable design. Can I start working on the same?

**Comment by liyasthomas** [comment]
@AndrewBastin thoughts on this?

**Comment by AndrewBastin** [comment]
I think storing metadata within collections regarding headers will work. During the Effective REST Request generation phase we just need to recursively traverse back the tree.

But this interestingly brings into the light some interesting side points we have to clear out.

1. Cascading – How the header fields cascade. (What happens when the headers are defined in multiple levels)

2. A UI representation – This increasingly obscures and makes it difficult to track the source of different header fields and actually the active header fields being applied onto a request and from where is a concern we have to not take lightly as this shoots up complexity on what has been a relatively easy to understand and use section of the app.

3. Disabling – We do offer options to disable header entries from a request, how are they going to be processed ?


Except point (2), rest all seem to be self explanatory. But these are meaningful points to be considered. The current implementation works and is simple and we are not trying to be another bloated complex API Request Builder so if we can communicate clearly what is happening and this is tucked away neatly unless explicitly required, we can go ahead with this.

**Comment by Shylajhaa** [comment]
@liyasthomas @kaname-png Thoughts?

**Comment by kaname-png** [comment]
@Shylajhaa I like the idea of being able to store metadata in the request folders, for example: when viewing the folder options there should also be an option called headers and depending on what headers there are, they will be applied to the other requests within the collection folder, and that there is an option in the requests that is to ignore the use of global headers for that folder.

**Comment by Tommyten** [comment]
@Shylajhaa Any news on this? This feature would be a great addition, I'm looking forward to

**Comment by AndyDonits** [comment]
@Shylajhaa It would be great to have this feature, currently I need to edit 150 requests manually because when I imported the collection from postman it didn't take into account the authorization from the postman collection

**Comment by RenanDore** [comment]
Hey devs, anyone have updates to this issue? Thanks!

**Comment by nfacha** [comment]
+1 on this, this is by far the thing I miss most from Postman

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.

Documentation: https://docs.hoppscotch.io/documentation/features/collections#collection-properties
