### ISSUE TITLE
how to use hoppscotch to download excel

### ISSUE THREAD

**Issue by q546948719** [hoppscotch/hoppscotch#1760]
I written an interface to export excel, how do i use hoppscotch to test it ?

**Comment by liyasthomas** [comment]
If it's available in an API endpoint, you can send a `GET` request to that endpoint from Hoppscotch request section to fetch its data.

But at the moment you can't view the interactive Excel data since there's no support to display excel files in Hoppscotch. Instead, you can view the `RAW` data in Hoppscotch response section.
