### ISSUE TITLE
Feature Request: Disable zooming in mobile PWA

### ISSUE THREAD

**Issue by JJTech0130** [hoppscotch/hoppscotch#1962]
**Is your feature request related to a problem? Please describe.**
Accidentally zooming in the PWA on iOS is very annoying, and makes it feel less like a native app. It makes it much harder to use.

**Describe the solution you'd like**
`user-scalable=no` or similar. Perhaps a toggle in the experiments section?

**Comment by liyasthomas** [comment]
Hi @JJTech0130, thanks for reporting this concern, but this is an intended behaviour.

Setting `user-scalable=no` or anything that restrict users from zooming in is an accessibility concern rather than maintaining an app like UI. Problematic for users with low vision who rely on browser zoom to see the contents of a web page.

In reality, Google degrade websites which restrict zooming. [Read more](https://web.dev/meta-viewport)

Will definitely see if putting a `maximum-scale` greater than `5` makes this experiance any better.

**Comment by JJTech0130** [comment]
That’s fine, just noting that I was only asking for an option in the PWA, which is supposed to act like a native app, and most native apps do not allow zooming. It’s especially annoying on my iPad, which apple suggests is going to become a “laptop” replacement, yet it is incredibly annoying to type when everything zooms in.
