### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [hoppscotch/hoppscotch#2056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

security bug

### Steps to reproduce

@li Hi a potential security vulnerability has been disclosed to huntr against your repo .
Plz validate this report https://huntr.dev/bounties/5135f71a-8acd-4ac2-ba45-52b1c78155bb

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
@ranjit-git please give us a little bit of time to triage and resolve the issue before opening up an issue in Github as we do follow huntr.dev reports closely so that we can reduce spam in the repo and also give us a chance to resolve the vulnerability under the hood before a fuilly public disclosure.

Also, I have left a comment on Huntr regarding the validity of this report.

Thank you for your effort!
