### ISSUE TITLE
[bug]: pnpm run generate dist filesize increase

### ISSUE THREAD

**Issue by baiy** [hoppscotch/hoppscotch#2069]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/2341581/149922276-5ca8b50c-6643-417a-8349-58f15ad39ac5.png)

dist-git-647c347 => <https://github.com/hoppscotch/hoppscotch/tree/647c347eb143096b162f4cda0a0217c195b3f60c>
dist-git-7f7338fa => <https://github.com/hoppscotch/hoppscotch/tree/7f7338faeb4f5336f2e84e7e9d27cdd6bbc393d6>

### Steps to reproduce

pnpm run install
pnpm run generate

### Environment

Production

### Version

Local

**Comment by AndrewBastin** [comment]
@baiy I don't see how this issue is of concern. Hence I am closing this issue for now.

We do not optimize for build sizes, we optimize for size of content transferred over the network by clients, hence Hoppscotch build generation generates a lot of code/assets which may or may not be used by the end user.

For an average user, Hoppscotch has to load about 5MB worth of network resources to be used, which is still a bit above my personal goal (~4MB). But 5MB is still not that bad.

Is there any specific reason you are worrying about build sizes ?
