### ISSUE TITLE
[bug]: "Could not send request", but request was sent, and a response has been received (reopened)

### ISSUE THREAD

**Issue by syrm** [hoppscotch/hoppscotch#2256]
Same problem with proxy turned on.
The problem is not related to CORS.

I mean even if CORS block the request, we should see this in Response section

_Originally posted by @syrm in https://github.com/hoppscotch/hoppscotch/issues/2255#issuecomment-1096753779_

**Comment by liyasthomas** [comment]
So, I tried the API endpoint you mentioned in the OP comment while the Proxy mode is turned ON. And I was able to get the expected behavior: `404 page not found`.

<img width="1440" alt="Screenshot 2022-04-12 at 7 35 04 PM" src="https://user-images.githubusercontent.com/10395817/162980501-165e1208-9c66-48e2-8668-71da58778a04.png">

Can you make sure the Proxy URL is given in Settings > Interceptor > Proxy is `https://proxy.hoppscotch.io/`

**Comment by syrm** [comment]
The proxy is correctly setup.
But we have a fairly complex infrastructure, let me check if something is blocked (i'll give an answer in few days)

**Comment by syrm** [comment]
Disabling the proxy and enabling the "Use the browser extension" it works.
Thanks you

**Comment by cherbear263** [comment]
> Disabling the proxy and enabling the "Use the browser extension" it works. Thanks you

This works. Thanks!
