### ISSUE TITLE
[feature]: Send binary file as body

### ISSUE THREAD

**Issue by metehus** [hoppscotch/hoppscotch#2594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would like to send a binary file as the body. There are some issues regarding this (#298), but this resolves to send a file using form-data. I would like to send the file as the entire body

### Why should this be worked on?

It is something that can happen, so it should be possible to do. Also, [amazon S3's PutObject api](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) requires that the file is sent via the body, and i can't do that using hoppscotch.
Btw, in postman, it is also possible to do that:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/22124518/185500717-0dadd9d3-d636-4694-b052-aa4ad8abf583.png">

**Comment by wisinfun** [comment]
This feature is very needed

**Comment by lucas-tavares-elevential** [comment]
Any updates? :eyes:

**Comment by kanonji** [comment]
I am also looking forward to this feature.

However, in my case, I used `application/x-www-form-encoded` as a workaround because I didn't care what data I uploaded.
After setting it up with "key: data, value: test", an object like a text file with `data=test` will be created in S3.

To tell S3 the Content-Type of the object, I also override the Content-Type with `text/plain` or `binary/octet-stream` depending on the situation.

**Comment by MarcelHoell** [comment]
This feature would be very nice!

**Comment by devguydavid** [comment]
I had so much hope for Hoppscotch! But this one issue is a showstopper for us.

I can understand there might be some complexity here with the way the UI is set up currently since, currently, one selects a content type and then provides the content. There are _many_  content types that files could represent. However, maybe it would work to allow the selection of some special menu item "from file" or something similar that allows the user to manually enter the content-type?

**Comment by devguydavid** [comment]
I also understand that this means Hoppscotch, in order to work reliably in the web-based version and especially when sharing with teams, would need to start storing files, potentially large files, and a lot of them.

I hope this can be figured out because so far, after spending a lot of time with a lot of different tools, I like Hoppscotch the best.

**Comment by ValeryP** [comment]
We need the ability to send binary files as the body, not just as form data. This is essential for working with APIs like Amazon S3's PutObject, which requires direct file uploads via the body. Currently, this limitation forces us to switch to other tools like Postman, breaking our workflow.

By implementing this feature, you'll make Hoppscotch far more versatile and a true go-to tool for API testing, especially for developers who need this functionality regularly. Let's get this done and make Hoppscotch a more powerful option for serious API work.

**Comment by eikaramba** [comment]
i think it is now implemented see https://github.com/hoppscotch/hoppscotch/pull/4466

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
