### ISSUE TITLE
[feature]: Keyboard shortcut for "Save" & "Don't Save"

### ISSUE THREAD

**Issue by nezam05** [hoppscotch/hoppscotch#2681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When navigating to a different saved request, if existing request is modified, a popup appears asking to Save or Don't Save the changed request. two keyboard shortcut attached to Save and Don't save button would help reduce mouse usage.

### Why should this be worked on?

Since its an webapp, mouse usage is high. Adding these shortcuts will help reduce mouse usage and increase workflow speed.

**Comment by Anuran12** [comment]
Hey @nezam05 I would like to work on this. Can you please give me some more details. Like after which button press the popup will appear etc.

**Comment by liyasthomas** [comment]
Hi @nezam05,
Fyi, whenever the "Save request" modal opens up, you can `Dismiss` the modal by pressing escape key [ <kbd>ESC</kbd> ] and confirm `Save` by pressing return key [ <kbd>⏎</kbd> ].

Hi @Anuran12,
We appreciate your interest in contributing to Hoppscotch. Since this feature already exists in the app, you may pick any other issue that suits your interest. Thank you.

Feature exists, hence closing.
