### ISSUE TITLE
[bug]: Identical (Non-Unique) collection names are allowed

### ISSUE THREAD

**Issue by Pranav-yadav** [hoppscotch/hoppscotch#2741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you create a new collection in under the API tabs (REST/GraphQL/Realtime), app's current logic **doesn't** checks if the same collection already exists.
As devs/testers/humans usually tend to use the similar names often, which could cause lot of confusions later, when they need to find the exact collection in hurry or while in HotFix mode :)

Find the attached ss if needed...

PS: You can assign this bug to me once confirmed, I'll try to fix it as part of #hacktoberfest22 as well as just because I like everything open source :)
 
<details>
<summary><h3>Screenshot</h3></summary>
<img src="https://user-images.githubusercontent.com/55224033/194127663-3e608682-ec89-4445-8ad6-ca6103d9a876.png" alt="Screenshot of: [bug]: Identical (Non-Unique) collection names are allowed">
</details>

### Steps to reproduce

1. Go to [https://hoppscotch.io](https://hoppscotch.io/)
2. Click on + icon btn to create/add new collection
3. Provide the unique name and click save/create
4. Repeat step 2
5. This time also provide the **same name** that you used in step 3
6. You're able to create multiple collections having same names

### Environment

Production

### Version

Cloud

**Comment by AlexHRodrii** [comment]
Can I work on this issue?

Thanks in advance

**Comment by liyasthomas** [comment]
Restricting users from creating collections with the same name is not a feature addition.

Since our current users might've created collections with similar names before, introducing this restriction for new users will be an anti-pattern. For those who think having duplicated collection names is an issue, they can always rename the duplicated collections to something unique. And for those who'd like to have duplicated collection names, we should keep this UX for now.
