### ISSUE TITLE
为什么页面的文字没法复制

### ISSUE THREAD

**Issue by wwg2017** [hoppscotch/hoppscotch#2821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

为什么页面的文字没法复制

### Why should this be worked on?

为什么页面的文字没法复制

**Comment by liyasthomas** [comment]
For Hoppscotch, we try to get the behaviour of a native application, instead of the usual internet behaviour of being able to select everything on screen.

For instance, for text that is part of the own application’s UI (like a toolbar, or a side menu), I think it’s ok to not allow the text to be selectable.

But for other areas like the input boxes, response section for example, we allow users to be able to select the text.
