### ISSUE TITLE
[feature]: Cmd + W -> Close only the current tab

### ISSUE THREAD

**Issue by magarrent** [hoppscotch/hoppscotch#3042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hey there!

Just request that when you have multiple tags and hit Cmd + W or Ctrl + W to close the tab, all the window closes, not the tab.

### Why should this be worked on?

I think it might be useful to other users too!

**Comment by liyasthomas** [comment]
I'm afraid we can't override the <kbd>CMD</kbd> <kbd>W</kbd> keyboard shortcut since it's been assigned to close the browser tab by all browsers in general.

Recently we introduced two new features that'll help you to achieve the same without hijacking the native browser-specific or OS-specific keyboard shortcuts.
1. Spotlight <kbd>CMD</kbd> <kbd>K</kbd>
	You can open the search and command spotlight modal and search for "Close tab" > Select "Close tab" to close the current tab.
2. Context menu on Tabs
	You can now right-click on a tab and select "Close tab" to close the current tab.

Since we don't encourage overriding native keybindings I'm closing this issue.

**Comment by filipre** [comment]
Hi @liyasthomas, is the limitation still the case with the new release of the desktop application? I noticed that <kbd>CMD</kbd> <kbd>W</kbd> also closes the desktop app. Given it's a native app now, can we overwrite <kbd>CMD</kbd> <kbd>W</kbd> to close the current tab instead?

**Comment by liyasthomas** [comment]
We're planning to revamp keyboard shortcuts to make it more intuitive. Hence I'm open to suggestions on what shortcuts could be added to the list.

**Comment by filipre** [comment]
Awesome! I just found https://github.com/hoppscotch/hoppscotch/issues/3520, let's keep the discussion there then :)
