### ISSUE TITLE
[bug]: hoppscotch UI not loading after self server setup

### ISSUE THREAD

**Issue by saikrishna434** [hoppscotch/hoppscotch#3080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i see this error in console

index.3f127683.js:68     POST http://localhost:3170/graphql net::ERR_CONNECTION_REFUSED
(anonymous) @ index.3f127683.js:68
uu @ index.3f127683.js:68
pO @ index.3f127683.js:68
Os.request @ index.3f127683.js:68
Os.<computed> @ index.3f127683.js:68
(anonymous) @ index.3f127683.js:67
o$ @ index.3f127683.js:70
Ay @ index.3f127683.js:79
performAuthInit @ index.3f127683.js:79
(anonymous) @ index.3f127683.js:94
(anonymous) @ index.3f127683.js:94
index.3f127683.js:67 Uncaught (in promise) Error: Network Error
    at tu (index.3f127683.js:67:8560)
    at w.onerror (index.3f127683.js:68:1947)

![Screenshot 2023-05-26 at 12 46 26 AM](https://github.com/hoppscotch/hoppscotch/assets/106073187/c3e8f359-fe37-4a3a-ac8e-a4b4bc5b25d1)

    
    
    

### Steps to reproduce

After setting up as per the documentation i see this error, when i did last week it worked pefect but with a new server and new installation setup, may be with any recent changes i was throwing this exception

### Environment

Deploy preview

### Version

Self-hosted

**Comment by liyasthomas** [comment]
Hi @saikrishna434, it seems the backend server is not configured properly.

_Can you share the link to the documentation that you followed to self-host Hoppscotch?_

I am afraid you're using an outdated installation process. I would like to inform you that, starting with v2023.4.0;

- **The prerequisites to self-host Hoppscotch on your own infrastructure have been changed.**
- **The build steps and installation process of Hoppscotch have been changed.**

To ensure a smooth installation process, we have made updates to the documentation.
The latest version can be found at [Getting started with Self-Host Hoppscotch](https://docs.hoppscotch.io/documentation/self-host/getting-started).
Please refer to this updated documentation for the most accurate and up-to-date instructions.

We apologize for any inconvenience caused by the recent changes to the steps for self-hosting Hoppscotch.

In case you encounter any issues or have any questions while following the new steps, please don't hesitate to ask for further assistance. We are here to help you resolve any problems and make your experience with Hoppscotch as seamless as possible.

I hope that the updated documentation will help you to self-host Hoppscotch on your new server.

**Comment by saikrishna434** [comment]
![Screenshot 2023-05-26 at 1 08 41 PM](https://github.com/hoppscotch/hoppscotch/assets/106073187/e2ee5f8e-e678-4fb6-98c9-7ed67881da76)

Yeah @liyasthomas , am using the same process see the version as mentioned and still i see the same error

**Comment by liyasthomas** [comment]
@saikrishna434 can you share your `.env` file contents to better understand the error? You can mask the variable values if there's any sensitive information in it.

**Comment by saikrishna434** [comment]
@liyasthomas  am using the default file no changes there just did cp from .env.example to .env

**Comment by liyasthomas** [comment]
> **Note**
> **The prerequisites to self-host Hoppscotch on your own infrastructure have been changed.**
> **The build steps and installation process of Hoppscotch have been changed.**

You're required to setup a backend server in order to self-host Hoppscotch.

To ensure a smooth installation process, we have made updates to the documentation.

Read the documentation: [Getting started with Self-Host Hoppscotch](https://docs.hoppscotch.io/documentation/self-host/getting-started) for information.

Look out for the latest [prerequisites](https://docs.hoppscotch.io/documentation/self-host/prerequisites) and [build steps](https://docs.hoppscotch.io/documentation/self-host/install-and-build) instructions.

Please refer to this updated documentation for the most accurate and up-to-date instructions.

**Comment by saikrishna434** [comment]
@liyasthomas  Again to mention i followed the same documentation and am getting the aforementioned error

**Comment by liyasthomas** [comment]
> @liyasthomas  am using the default file no changes there just did cp from .env.example to .env

You need to populate the `.env` file with your own keys as described in the [Install and build](https://docs.hoppscotch.io/documentation/self-host/install-and-build#configuring-the-environment) section. The sample given in `.env.example` won't work.

To help us debug the error, you need to share the masked contents of your `.env` file.

**Comment by saikrishna434** [comment]
@liyasthomas  thanks, after updating the env file with local public ip instead of localhost i see this page
![Screenshot 2023-05-26 at 3 27 39 PM](https://github.com/hoppscotch/hoppscotch/assets/106073187/c6527775-9f41-4616-b42a-1fcd88287b12)

may be i need to configure OAUTH for getting in

**Comment by liyasthomas** [comment]
Glad it worked out for you. Feel free to reopen the issue if you need any further assistance with Hoppscotch.
