### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by tugrulaslan** [hoppscotch/hoppscotch#3400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We have been testing the app on our self-hosted AWS infra. While trying things out, I have encountered a minor UI issue in the Authorization Bearer token part. After inserting a valid and long JWT token into the input form, the UI stretches horizontally and the input form is not nearly visible. The issue shown below

<img width="1165" alt="Screenshot 2023-09-28 at 09 36 18" src="https://github.com/hoppscotch/hoppscotch/assets/3064404/43919a8e-8c6f-4a97-bf79-c49c7175a94f">

Browser: Firefox 117.0.1 (64-bit)
OS: Macos 13.6 (22G120)
Product Version: 2023.8.0

### Steps to reproduce

1. Go to the graphql
2. Add the server url
3. add the query,
4. switch to the Authorization, select Authroization Type Bearer and add the long JWT

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment]
This was a known issue in Firefox browsers which got fixed in Hoppscotch v2023.8.1 via #3362.

Can you make sure you're on the latest version of Hoppscotch v2023.8.1?

<img width="1470" alt="Screenshot 2023-09-28 at 1 26 34 PM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/8ee4af88-6154-4242-8d24-c8a1b0162408">

**Comment by tugrulaslan** [comment]
@liyasthomas now we have upgraded and i can confirm that since the version 2023.8.1, the UI works fine thank you
