### ISSUE TITLE
[bug]: Secrets variable not persistent

### ISSUE THREAD

**Issue by Leon-Luu** [hoppscotch/hoppscotch#3879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When created a Secret variables and saved. After logout and login from the Hoppscotch the secrets are lost. Show secret is not showing any values anymore.
This is easy to reproduce with incognito modes or changing browsers.
The same issue happens on the secrets within the local workspaces and the Team environment secrets.

![image](https://github.com/hoppscotch/hoppscotch/assets/88329746/566d489c-8c25-4f0b-82ab-230bd4fb22d8)

After login secrets values disappeared:
![image](https://github.com/hoppscotch/hoppscotch/assets/88329746/3f125796-7f0d-47fe-9e1d-8a5d797615a5)

### Steps to reproduce

1) create Sercret variables  with values and save
2) Logout and login ( incognito mode or change to another browser)
3) Check the secret values again

### Environment

Production

### Version

Cloud

**Comment by thetronjohnson** [comment]
Hi @Leon-Luu, This is the expected behavior for secret variables. Because secrets variables can be used to store sensitive information such as passwords or other credentials, the secret variable values are never synced with Hoppscotch.

https://docs.hoppscotch.io/documentation/features/environments#types-of-variables-in-an-environment
