### ISSUE TITLE
[bug]: Large images on the main (landing) website

### ISSUE THREAD

**Issue by altrusl** [hoppscotch/hoppscotch#3952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

I haven't found  a repo for your main websitу (hoppscotch.com) so leaving it here

### Current behavior

When users opens https://hoppscotch.com/blog or other pages on that subdomain they see images of enormous dimension and  file size
For example: [https://hoppscotch.com/images/blog-hoppscotch-wrapped-2023.png](https://hoppscotch.com/images/blog-hoppscotch-wrapped-2023.png) takes 8.53Mb
Its loading time is huge both for desktop and for mobile clients

### Expected behavior

Proper image format (webp), dimension and file size

### Steps to reproduce

1. Go to https://hoppscotch.com/blog
2. Check out image sizes

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Thanks for bringing this up.

I've added a build step to compress and optimize all image assets (png, jpeg, gif, tiff, webp, avif) using [Sharp.js](https://github.com/lovell/sharp) and SVG assets using [SVGO](https://github.com/svg/svgo).

Here's the output:

---

<img width="1059" alt="Screenshot 2024-03-30 at 12 53 04 PM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/2d26b5e7-4542-4657-9e5b-77aa4318ce76">

---

We'll see if we can optimize assets further. Since the initial changes are in production, I'll close this issue for now. Let us know if you find any other issues with the Hoppscotch platform.

**Comment by altrusl** [comment]
Your quick reaction confirms the high quality of your project and product )

Thank you

For the future - image dimensions can be reduced too. They are like: 4800x2700. 
It will greatly improve your Core Web Vitals. Especially using `<picture>` with 2-3 image size variants

![image](https://github.com/hoppscotch/hoppscotch/assets/29726515/ae6ecfba-58f5-448c-aea2-90fdc0422d7f)
