### ISSUE TITLE
[bug]: Unable to install Client on Ubuntu 24.04

### ISSUE THREAD

**Issue by pisandelli** [hoppscotch/hoppscotch#4235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to install, a dependency error is thrown.  

```bash
The following packages have unmet dependencies:
 hoppscotch : Depends: libwebkit2gtk-4.0-37 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

The package `libwebkit2gtk-4.1-0` is already installed!

### Steps to reproduce

1. Try to install the package using `sudo dpkg -i Hoppscotch_linux_x64.deb`
2. Check the error
3. Try to install the package using `sudo apt install ./Hoppscotch_linux_x64.deb`
4. Same Error
5. Try to bypass package installation `sudo dpkg -i --ignore-depends=libwebkit2gtk-4.0-37 ./Hoppscotch_linux_x64.deb`
5.1 The package is installed but does not start.

### Environment

Production

### Version

Local

**Comment by Jooraz** [comment]
This is caused by dependencies coming from tauri about which you can read in here: https://github.com/tauri-apps/tauri/issues/9662. TLDR is basically that, the references in hoppscotch-desktop would have to be updated to v2 of tauri (right now rc.1 is available, which is suboptimal). Also after performing the migration, more code changes in [packages/hoppscotch-selfhost-desktop/src/platform/auth.ts](https://github.com/hoppscotch/hoppscotch/blob/4fd6d6ddb4333e3d237f48d3ce01136d9f3f7f94/packages/hoppscotch-selfhost-desktop/src/platform/auth.ts) would have to be made, as `@tauri-apps/plugin-http` (from v2) is not having both `Body` and `getClientfrom` in it, unlike previously was in `@tauri-apps/api/http`. Not sure if they will be providing this in the future or Auth will need to be redesigned in the end.

However for a now as a **workaround**, what you can find in the [9662](https://github.com/tauri-apps/tauri/issues/9662#issuecomment-2144939700) issue is a link to [clash-verge-rev dependencies](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/dependencies). Once I've installed them both on fresh Ubuntu 24.04, hoppscotch desktop started completely fine

**Comment by pisandelli** [comment]
Thanks, @Jooraz!
I've installed these packages and now Hoppscotch is working!  
Hope this problem with Tauri get resolved soon!

**Comment by Jooraz** [comment]
@pisandelli don't think they will, this issue is rolling for 3 months already

**Comment by varunvilva** [comment]
Thanks @Jooraz installing Hoppscotch after downloading these 2 packages helped me!!! :)
- https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libjavascriptcoregtk-4.0-18_2.43.3-1_amd64.deb 
- https://github.com/clash-verge-rev/clash-verge-rev/releases/download/dependencies/libwebkit2gtk-4.0-37_2.43.3-1_amd64.deb

**Comment by pisandelli** [comment]
deb Package is now installing without any hassle.
Tested on Ubuntu 25.04
Thanks!
