### ISSUE TITLE
[bug]: Can See Collections, Requests, etc...When Logged Out

### ISSUE THREAD

**Issue by jimmybrancaccio** [hoppscotch/hoppscotch#4287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I leave a Hoppscotch open in a tab for a couple days I am automatically logged out (expected). However when I bring up the tab and even refresh the page I am still seeing my workspace, collections, requests, etc...this is definitely not expected. Of note, I am self-hosting on v2024.7.1.

### Steps to reproduce

1. Setup a self-hosted Hoppscotch instance using v2024.7.1.
2. Create yourself an account, and log into it.
3. Create a couple collections with some requests in each of them.
4. There's probably a way to simulate being automatically logged out, but in my case I'll just have Hoppscotch open in a tab in my web browser and won't use it for a few days. When I come back to it, it's automatically logged me out.
5. Observe that you're still able to see your collections, requests, etc...while not being logged in.
6. Observe that even after refreshing the page/tab still shows your collections, requests, etc...

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment]
Thank you for bringing this to our attention.

This behavior is expected due to the way Hoppscotch manages personal workspace data. When you use Hoppscotch, your workspace, collections, and requests are initially stored in your browser's local storage. This allows you to work offline and ensures that your data is available even if you're not actively connected to the internet or logged in.

When you're automatically logged out after a period of inactivity, Hoppscotch retains your workspace data locally. That's why, even though you're logged out, you can still see your collections and requests. Refreshing the page doesn't clear this local storage, so your data remains visible.

To fully clear this data, you would need to manually clear your browser's local storage or log back into your account, at which point Hoppscotch will resync with the cloud and ensure that only data associated with your logged-in account is accessible.

If this behavior is a concern for your use case, consider logging out manually after each session and clearing offline data associated with Hoppscotch to avoid leaving data accessible on your device.

See this guide for Chrome browser:
[How to Automatically Clear Browsing Data When Closing Google Chrome Window: A Step-by-Step Guide](https://support.google.com/chrome/community-guide/245444314/how-to-automatically-clear-browsing-data-when-closing-google-chrome-window-a-step-by-step-guide?hl=en)

Let us know if you have any other questions or concerns!

**Comment by jimmybrancaccio** [comment]
Interesting. I've just never come across a piece of software or service that shares/shows data specific to an account when the account is not logged in. 🤨🤷🏼

**Comment by jimmybrancaccio** [comment]
@liyasthomas Apologies to resurrect this almost a year later. I understand your use case and while it seems a little weird, can you confirm it only allows you to work on things within your personal workspace? It doesn't allow you access to your other workspaces you've created, and requests within them, right? If so, how come?

Thanks! ☺️

**Comment by edlyra** [comment]
Thanks for the clarification on why this was closed.

I understand the current behavior is intentional to preserve offline/disconnected continuity, which makes sense.

However, I think there is still room for an optional privacy-focused improvement: allowing users to choose whether local collections/environments/workspace data should be cleared on explicit logout only.

To avoid mixing this with the original closed issue, I will open a separate feature request for that proposal and reference this discussion there.
