### ISSUE TITLE
[bug]: Latest version of the app [Version 24.9.0-0 (20241004.123034)] does not picks up environment variables

### ISSUE THREAD

**Issue by girish2711** [hoppscotch/hoppscotch#4403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I had old version of the app installed and there was a workspace and set of environment variables are defined
Updated to latest Version: 24.9.0-0 (20241004.123034)  [ Mac silicon version ]
I can see all environments defined
However, If I select and then choose my API, variables (like my host, http header params) show in red
If I mouse hover it says "Choose an environment [not found]", but environment is chosen and I can see that variable in evnironment tab

### Steps to reproduce

1. Define environment in older version
2. Update to latest version
3. Choose work space and choose environment
4. Variables like host and http param values will not get updated

### Environment

Production

### Version

Local

**Comment by slogivewd** [comment]
Same here

**Comment by slogivewd** [comment]
![image](https://github.com/user-attachments/assets/36c7251c-edcd-4158-abe3-5ae0e159b371)

**Comment by LuizSivan** [comment]
it seems to be desktop problem, working fine on web version

**Comment by mrdnr** [comment]
Unfortunately, I had a similar problem. The saved environment was deleted.

**Comment by girish2711** [comment]
Yes, Issue persists after app restart, reinstallation, closing all tabs, reloading. (restarted machine too !! ) 
Environments are team environments ( My other team mates may be still with older version) 
It is desktop app. Apple M3 Max Sonoma v14.4

**Comment by AndrewBastin** [comment]
Hi there,

We have an idea that the regression is caused by some bugs in how Hoppscotch migrates environments when there is data structure change from one version to the other. Particularly in Global Environments. We are working on a fix that we should be putting out by the end of the day.


In the meantime, please do downgrade to the previous version using this URL: https://github.com/hoppscotch/releases/releases/tag/v24.8.3-0

Really sorry about the inconvenience caused 🙇

**Comment by jamesgeorge007** [comment]
Hi, we have a [patch release](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.9.1) out. Please let us know if the issue persists.
